# .github/workflows/backend-publish.yml dd
name: Build & Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-publish.yml'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1. 코드 체크아웃
      - uses: actions/checkout@v3

      # 2. Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. 이미지 빌드 & 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/load-test-cicd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/load-test-cicd:${{ github.sha }}